name: Build and Deploy to ACR

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}    
     
    # deploy container app with updated images
    - name: 'Deploy app'
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: e93d3ee6-fac1-412f-92d6-bfb379e81af2
        resourceGroupName: CH3-Forrester
        template: ./main.bicep
        failOnStdErr: false
